First iteration: logger, storage, integration/unit tests, app skeleton
v4-nikishin/db-migrator pull request #1
Opened 2023-02-08 18:13 UTC by v4-nikishin

2023-02-08 19:49 UTC, gna69 requested changes

2023-02-08 19:49 UTC, gna69 commented on internal/storage/storage.go
> +	query := "insert into migrations (name, date, status) values ($1, $2, $3)"
Чтобы не выделять память на эти запросы каждый раз при вызове метода, можно унести эти запросы в константы.

2023-02-08 19:49 UTC, gna69 commented on internal/storage/storage.go
> +	if err != nil {
Можно заинлайнить: `if err := row.Scan(&m.Name, &m.Date, &m.Status); err != nil {`

2023-02-09 09:17 UTC, v4-nikishin commented on internal/storage/storage.go
> +	if err != nil {
done

2023-02-09 09:17 UTC, v4-nikishin commented on internal/storage/storage.go
> +	query := "insert into migrations (name, date, status) values ($1, $2, $3)"
done

2023-02-09 09:18 UTC, merged