Second iteration: implemented migration/parser/tests
v4-nikishin/db-migrator pull request #2
Opened 2023-02-15 16:55 UTC by v4-nikishin

2023-02-15 20:04 UTC, gna69 requested changes

2023-02-15 20:04 UTC, gna69 commented on internal/app/app.go
> +	sts, err := p.UpMigration()
Если переменная "p" больше нигде не нужна в коде, то можно обойтись без выделения памяти и заинлайнить: `sts, err := parser.New(a.log, filePath).UpMigration()`

2023-02-15 20:04 UTC, gna69 commented on internal/parser/parser.go
> +		p.log.Info(line)
Логи для дебага лучше выводить в соответсвующий Debug уровень логирования, так как они существенно замедляют работу приложения. В уровень info принято выводить важную информацию

2023-02-15 20:04 UTC, gna69 commented on internal/parser/parser.go
> +	return strings.HasSuffix(prev, ";")
Думаю
 можно не перебирать всю строку целиком, а взять сразу ее последнее слово и проверить есть ли точка с зяпятой. А в целом стоит проверять последний символ, потому что если между последним словом и ; стоит n пробелов - такой sql код так же будет корректен.

2023-02-16 15:02 UTC, v4-nikishin commented on internal/app/app.go
> +	sts, err := p.UpMigration()
исправил

2023-02-16 15:02 UTC, v4-nikishin commented on internal/parser/parser.go
> +		p.log.Info(line)
исправил

2023-02-16 15:02 UTC, v4-nikishin commented on internal/parser/parser.go
> +	return strings.HasSuffix(prev, ";")
учту

2023-02-16 15:02 UTC, merged